import { motion } from 'framer-motion';

export default function HighlightsPlayer() {
  return (
    <div className="glass-card p-6 border-cyan-500/20 bg-cyan-500/5 relative overflow-hidden">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h3 className="text-[10px] font-black text-cyan-400 uppercase tracking-[0.2em]">AI Cinematic Highlights</h3>
          <p className="text-[8px] font-black text-gray-500 uppercase tracking-widest mt-1">Generated by NarrativeAgent</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-1.5 bg-red-500 rounded-full animate-pulse" />
          <span className="text-[8px] font-black text-white uppercase tracking-widest">Processing...</span>
        </div>
      </div>

      <div className="relative aspect-video bg-black rounded-2xl border border-white/5 overflow-hidden group">
        <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/60 opacity-100 group-hover:bg-black/40 transition-all">
          <div className="w-16 h-16 rounded-full bg-cyan-500 flex items-center justify-center text-black text-2xl shadow-[0_0_30px_rgba(6,182,212,0.3)] cursor-pointer hover:scale-110 transition-transform">
            ▶
          </div>
          <p className="text-[10px] font-black text-white uppercase tracking-[0.3em] mt-6">Watch Match Reel</p>
        </div>
        
        {/* Visual Mock for "Processing" */}
        <div className="absolute bottom-0 left-0 w-full h-1 bg-white/5">
          <motion.div 
            initial={{ width: 0 }}
            animate={{ width: '70%' }}
            className="h-full bg-cyan-500 shadow-[0_0_100px_rgba(6,182,212,1)]"
          />
        </div>
      </div>

      <div className="mt-4 grid grid-cols-2 gap-4">
        <button className="py-3 bg-white/5 border border-white/10 rounded-xl text-[8px] font-black uppercase tracking-widest hover:bg-white/10 transition-all">
          Full Replay
        </button>
        <button className="py-3 bg-cyan-500 text-black rounded-xl text-[8px] font-black uppercase tracking-widest">
          Share Reel
        </button>
      </div>
    </div>
  );
}
